# Generated by Django 6.0.2 on 2026-04-14 13:56

import django.db.models.deletion
import registration.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TouristRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=registration.models.generate_token, max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('id_number', models.CharField(max_length=50)),
                ('transport_mode', models.CharField(max_length=20)),
                ('checkpoint', models.CharField(max_length=100)),
                ('entry_date', models.DateTimeField(auto_now_add=True)),
                ('stay_duration', models.IntegerField()),
                ('activated', models.BooleanField(default=False)),
                ('qr_code', models.ImageField(blank=True, upload_to='qr_codes/')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
